# Generated by Django 4.2.6 on 2023-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='голос',
            field=models.IntegerField(default=0, verbose_name='голосов'),
        ),
    ]
